import {Run,SAVE_KEY,normalizeSave,stats,purchase,upgradeCost,UPGRADE_DEFS,BOONS,ZONES} from './core.mjs';
import {World} from './view.js';
import {Sound} from './audio.js';
const $=id=>document.getElementById(id);
let save,storageOK=true;
try{save=normalizeSave(JSON.parse(localStorage.getItem(SAVE_KEY)||'{}'));}catch{save=normalizeSave();storageOK=false;}
const persist=()=>{try{localStorage.setItem(SAVE_KEY,JSON.stringify(save));storageOK=true;}catch{storageOK=false;}$('save-warning').classList.toggle('hidden',storageOK);};
const sound=new Sound(save.settings.sound);
let world,run=null,screen='home',returnScreen='home',paused=false,calloutUntil=0,uiTime=0,frameTime=0,slowFrames=0,last=performance.now(),raf=0;
let pointer=null;
const screens=['home','workshop','result','help','settings','paused','blessing'];
function show(name){screen=name;for(const s of screens)$(s).classList.toggle('hidden',s!==name);const running=name==='running';$('hud').classList.toggle('hidden',!running&&name!=='paused');$('run-controls').classList.toggle('hidden',!running);if(!running)$('training').classList.add('hidden');if(name==='home')home();if(name==='workshop')workshop();if(name==='settings')settings();pointer=null;}
function home(){ $('best').textContent=save.best.toLocaleString();$('wallet').textContent=save.wallet.toLocaleString();const n=UPGRADE_DEFS.filter(u=>save.levels[u.id]<12&&upgradeCost(save.levels[u.id])<=save.wallet).length;$('upgrade-badge').textContent=n?'強化できます':'';$('start').textContent=save.runs?'もう一度、遺跡へ →':'遺跡へ走り出す →';$('save-warning').classList.toggle('hidden',storageOK);}
function start(){sound.unlock();run=new Run(save);paused=false;for(const [id,g]of world.objectViews){world.scene.remove(g);(world.pool[g.userData.type]??=[]).push(g);}world.objectViews.clear();$('callout').classList.remove('visible');$('sky').style.filter='';$('flash').style.opacity=0;show('running');updateHUD();announce(run.training?'灯火の旅が、はじまる':'AURELIA',run.training?'最初の190mは、失敗しても大丈夫':'2,500m先の秘宝へ',2);}
function announce(title,sub='',seconds=1.1){$('callout').replaceChildren();$('callout').append(document.createTextNode(title));if(sub){const small=document.createElement('small');small.textContent=sub;$('callout').append(small);}$('callout').classList.add('visible');calloutUntil=performance.now()+seconds*1000;}
function workshop(){ $('shop-wallet').textContent=save.wallet.toLocaleString();$('upgrades').replaceChildren();for(const u of UPGRADE_DEFS){const lv=save.levels[u.id],cost=upgradeCost(lv);const div=document.createElement('div');div.className='upgrade';div.innerHTML=`<span class="upgrade-icon">${u.icon}</span><div><h3>${u.name}</h3><p>${u.text}</p><p>${u.detail}</p><div class="level">LEVEL ${lv} / 12</div><div class="upgrade-meter">${Array.from({length:12},(_,i)=>`<i class="${i<lv?'on':''}"></i>`).join('')}</div></div>`;const b=document.createElement('button');b.textContent=lv>=12?'MAX':`✧ ${cost.toLocaleString()}`;b.setAttribute('aria-label',`${u.name}を強化、結晶${cost}`);b.disabled=lv>=12||save.wallet<cost;b.onclick=()=>{sound.unlock();if(purchase(save,u.id)){persist();sound.effect('purchase');workshop();}};div.append(b);$('upgrades').append(div);}}
function settings(){ $('sound-setting').checked=save.settings.sound;$('buttons-setting').checked=save.settings.buttons;$('quality-setting').value=save.settings.quality;$('save-status').textContent='';}
function finish(){const reward=run.settle();if(!reward)return;persist();$('result-eyebrow').textContent=run.won?'THE DAWN IS YOURS':'EXPEDITION COMPLETE';$('result-title').textContent=run.won?'暁の秘宝、その手に。':'次の一歩へ。';$('result-reason').textContent=run.reason;$('result-distance').textContent=Math.floor(run.distance).toLocaleString();$('new-record').classList.toggle('hidden',!reward.record);$('result-zone').textContent=ZONES[run.zone];$('result-perfect').textContent=run.perfect+run.dodges;$('result-combo').textContent=run.maxCombo;$('result-gems').textContent=run.coins;$('result-reward').textContent=reward.total.toLocaleString();$('reward-detail').textContent=`拾った結晶 ${reward.coins} + 距離 ${reward.exploration} + 挑戦 ${reward.challenge}${reward.clear?' + 秘宝 '+reward.clear:''}${reward.bonus?' + 強化・祝福 '+reward.bonus:''}`;const can=UPGRADE_DEFS.some(u=>save.levels[u.id]<12&&upgradeCost(save.levels[u.id])<=save.wallet);$('result-tip').textContent=run.won?'旅は、あなたのもの。装備を磨き、さらに美しい走りを。':can?'装備を強化できます。次の探索を、少し先へ。':run.energy<=0?'青い灯りと華麗な回避で灯火を補給。ランタンの強化も助けになります。':'高い石柱は横へ、低い障害物は上へ。少し早めのスワイプがコツです。';show('result');$('speed-lines').classList.remove('active');$('game').classList.remove('boosting');}
function blessing(){ $('blessing-title').textContent=ZONES[run.zone]+'へ';$('boons').replaceChildren();for(const boon of BOONS){const b=document.createElement('button');b.className='boon';b.innerHTML=`<span>${boon.icon}</span><div><b>${boon.name}</b><small>${boon.text}</small></div>`;b.onclick=()=>{sound.unlock();run.chooseBoon(boon.id);show('running');announce(boon.name,'新しい道へ',1.8);};$('boons').append(b);}show('blessing');}
function pause(){if(screen!=='running'||!run||run.state!=='running')return;paused=true;show('paused');sound.suspend();}
function resume(){if(!run)return;sound.unlock();paused=false;show('running');last=performance.now();announce('探索再開','',.8);}
function action(a){if(screen!=='running'||paused)return;sound.unlock();run.input(a);}
function updateHUD(){if(!run)return;$('distance').textContent=Math.floor(run.distance).toLocaleString();$('zone-name').textContent=`0${run.zone+1} / ${ZONES[run.zone]}`;$('journey-fill').style.width=`${Math.min(100,run.distance/25)}%`;$('energy-text').textContent=Math.ceil(run.energy);$('energy-fill').style.transform=`scaleX(${Math.max(0,run.energy/run.stat.energy)})`;document.querySelector('.lamp').classList.toggle('low',run.energy/run.stat.energy<.23);$('hp').textContent='◆ '.repeat(Math.max(0,run.hp))+'◇ '.repeat(Math.max(0,run.stat.hp-run.hp));$('hp').setAttribute('aria-label',`耐久力 ${run.hp} / ${run.stat.hp}`);$('coins').textContent=run.coins;$('boost-fill').style.width=run.charge+'%';$('boost').disabled=run.charge<100||run.boost>0;$('boost').classList.toggle('ready',run.charge>=100);$('boost-label').textContent=run.boost>0?'共鳴ダッシュ！':run.charge>=100?'タップで共鳴ダッシュ':'共鳴をためる';$('boost-percent').textContent=run.boost>0?`${run.boost.toFixed(1)} s`:run.charge>=100?'無敵で一気に駆け抜ける':`${Math.floor(run.charge)}%`;$('touch-buttons').classList.toggle('hidden',!save.settings.buttons);$('speed-lines').classList.toggle('active',run.boost>0);$('game').classList.toggle('boosting',run.boost>0);
  let guide=null;if(run.training&&run.distance<188){const d=run.distance;if(d<68)guide=['↑','上へスワイプ','金色の低い壁をジャンプ'];else if(d<118)guide=['↓','下へスワイプ','青緑色の梁の下をスライド'];else if(d<170)guide=['↔','左右へスワイプ','高い石柱は横にかわす'];else guide=['☀','青い灯りを拾おう','灯火が回復。結晶は強化の資金に'];}$('training').classList.toggle('hidden',!guide||screen!=='running');if(guide){$('training-icon').textContent=guide[0];$('training-title').textContent=guide[1];$('training-copy').textContent=guide[2];}
}
function processEvents(){for(const e of run.events.splice(0)){sound.effect(e.type,run.combo);world.event(e,run);if(e.type==='perfect')announce('FLOW',`灯火 +5 · ${e.combo} COMBO`);if(e.type==='dodge')announce('CLOSE CALL',`共鳴 +7 · ${e.combo} COMBO`);if(e.type==='ready')announce('RESONANCE READY','下のボタンで、無敵ダッシュ',1.8);if(e.type==='boost')announce('RESONANCE','光になれ。',1.3);if(e.type==='flame')announce('灯火 +12','',.65);if(e.type==='hit'||e.type==='practice'){$('flash').style.background=e.type==='hit'?'#d36449':'#9cd4be';$('flash').style.opacity='.3';if(e.type==='practice')announce('大丈夫、もう一度。','練習中は耐久力が減りません',1.2);}if(e.type==='gate'){$('sky').style.filter=run.zone===1?'hue-rotate(17deg) saturate(.78) brightness(.73)':'sepia(.18) saturate(1.1)';blessing();}if(e.type==='end')finish();}}
function frame(now){raf=requestAnimationFrame(frame);const realDt=Math.min(.1,(now-last)/1000);last=now;if(document.hidden)return;const active=screen==='running'&&!paused&&run?.state==='running';if(active){let remaining=realDt;while(remaining>0&&run.state==='running'){const step=Math.min(remaining,1/60);run.step(step);remaining-=step;}processEvents();}if(run&&!active&&run.events.length)processEvents();const visualRun=['home','help','settings','workshop'].includes(screen)?null:run;world.update(visualRun,Math.min(realDt,.033),active);sound.update(active,run?.boost>0);uiTime+=realDt;if(uiTime>.08){uiTime=0;if(run)updateHUD();}if(now>calloutUntil)$('callout').classList.remove('visible');const opacity=parseFloat($('flash').style.opacity)||0;if(opacity>0)$('flash').style.opacity=Math.max(0,opacity-realDt*1.5);if(save.settings.quality==='auto'&&!world.low&&active){frameTime+=realDt;if(realDt>.030)slowFrames++;if(frameTime>4){if(slowFrames>55){world.low=true;world.renderer.shadowMap.enabled=false;world.resize();}frameTime=0;slowFrames=0;}}}
$('start').onclick=start;$('shop-start').onclick=start;$('retry').onclick=start;
$('workshop-open').onclick=()=>{returnScreen='home';show('workshop');};$('result-upgrade').onclick=()=>{returnScreen='result';show('workshop');};$('result-home').onclick=()=>show('home');$('help-open').onclick=()=>{returnScreen='home';show('help');};$('settings-open').onclick=()=>{returnScreen='home';show('settings');};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>show(returnScreen));
$('pause').onclick=pause;$('resume').onclick=resume;$('retire').onclick=()=>{paused=false;run.end('結晶を携えて帰還した');processEvents();};$('boost').onclick=()=>action('boost');
document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('pointerdown',e=>{e.preventDefault();action(b.dataset.action);}));
$('sound-setting').onchange=e=>{save.settings.sound=e.target.checked;sound.setEnabled(save.settings.sound);persist();};$('buttons-setting').onchange=e=>{save.settings.buttons=e.target.checked;persist();};$('quality-setting').onchange=e=>{save.settings.quality=e.target.value;world.setQuality(e.target.value);persist();};
$('world').addEventListener('pointerdown',e=>{if(screen!=='running')return;e.preventDefault();if(pointer)return;pointer={id:e.pointerId,x:e.clientX,y:e.clientY,used:false};try{$('world').setPointerCapture(e.pointerId);}catch{}});
$('world').addEventListener('pointermove',e=>{if(!pointer||pointer.id!==e.pointerId||pointer.used)return;e.preventDefault();const dx=e.clientX-pointer.x,dy=e.clientY-pointer.y;const threshold=Math.max(22,Math.min(36,$('game').clientWidth*.055));if(Math.max(Math.abs(dx),Math.abs(dy))<threshold)return;pointer.used=true;action(Math.abs(dx)>Math.abs(dy)?dx<0?'left':'right':dy<0?'jump':'slide');});
for(const type of ['pointerup','pointercancel','lostpointercapture'])$('world').addEventListener(type,e=>{if(pointer?.id===e.pointerId)pointer=null;});
document.addEventListener('gesturestart',e=>e.preventDefault(),{passive:false});document.addEventListener('contextmenu',e=>e.preventDefault());document.addEventListener('touchmove',e=>{if(screen==='running')e.preventDefault();},{passive:false});
const keys={ArrowLeft:'left',a:'left',A:'left',ArrowRight:'right',d:'right',D:'right',ArrowUp:'jump',w:'jump',W:'jump',ArrowDown:'slide',s:'slide',S:'slide',' ':'boost'};
window.addEventListener('keydown',e=>{if(e.target instanceof HTMLInputElement||e.target instanceof HTMLSelectElement)return;if(e.key==='Escape'){e.preventDefault();screen==='paused'?resume():pause();return;}if(keys[e.key]&&screen==='running'){e.preventDefault();if(!e.repeat)action(keys[e.key]);}});
document.addEventListener('visibilitychange',()=>{if(document.hidden){pause();sound.suspend();persist();}else last=performance.now();});window.addEventListener('pagehide',()=>{pause();persist();});window.addEventListener('blur',pause);
let resizeTimer;const resize=()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>world?.resize(),80);};window.addEventListener('resize',resize);window.visualViewport?.addEventListener('resize',resize);
$('world').addEventListener('webglcontextlost',e=>{e.preventDefault();pause();persist();cancelAnimationFrame(raf);$('error-detail').textContent='描画が中断されました。強化と記録は保存されています。ページを読み込み直してください。';$('error').classList.remove('hidden');});
$('export-save').onclick=()=>{persist();const data={game:'aurelia',version:1,savedAt:new Date().toISOString(),data:save};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='aurelia-save.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('save-status').textContent='セーブを書き出しました。ファイルを保管してください。';};
$('import-save').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>64000)throw new Error('size');const json=JSON.parse(await file.text());if(json.game!=='aurelia'||json.version!==1||!json.data?.levels)throw new Error('format');const loaded=normalizeSave(json.data);if(!confirm(`結晶 ${loaded.wallet}・最長 ${loaded.best}m のセーブを読み込みます。現在の記録を置き換えますか？`))return;save=loaded;persist();sound.setEnabled(save.settings.sound);world.setQuality(save.settings.quality);settings();$('save-status').textContent='セーブを読み込みました。';}catch{$('save-status').textContent='AURELIAのセーブファイルを選んでください。';}finally{e.target.value='';}};
async function boot(){try{world=new World($('world'),save.settings.quality);world.update(null,0,false);show('home');persist();window.aureliaReady=true;$('loading').classList.add('hidden');last=performance.now();raf=requestAnimationFrame(frame);}catch(err){console.error(err);$('loading').classList.add('hidden');$('error-detail').textContent='3D描画を開始できませんでした。Safariを更新して開き直してください。';$('error').classList.remove('hidden');}}
boot();
