export class Sound {
  constructor(enabled=true){this.enabled=enabled;this.ctx=null;this.nextMusic=0;this.phrase=0;}
  unlock(){if(!this.enabled)return;try{if(!this.ctx){const Audio=window.AudioContext||window.webkitAudioContext;this.ctx=new Audio();this.master=this.ctx.createGain();this.master.gain.value=.32;this.master.connect(this.ctx.destination);this.music=this.ctx.createGain();this.music.gain.value=.15;this.music.connect(this.master);}if(this.ctx.state==='suspended')this.ctx.resume().catch(()=>{});}catch{this.enabled=false;}}
  setEnabled(enabled){this.enabled=enabled;if(enabled)this.unlock();if(this.master)this.master.gain.setTargetAtTime(enabled?.32:0,this.ctx.currentTime,.1);}
  tone(freq,duration=.2,type='sine',volume=.2,delay=0,end=null,bus=null){if(!this.enabled||!this.ctx||this.ctx.state!=='running')return;const c=this.ctx,t=c.currentTime+delay,o=c.createOscillator(),g=c.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);if(end)o.frequency.exponentialRampToValueAtTime(end,t+duration);g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(volume,t+.012);g.gain.exponentialRampToValueAtTime(.001,t+duration);o.connect(g);g.connect(bus||this.master);o.start(t);o.stop(t+duration+.03);o.onended=()=>{o.disconnect();g.disconnect();};}
  effect(type,combo=0){if(type==='coin')this.tone(780+Math.min(8,combo)*52,.14,'sine',.14);if(type==='jump')this.tone(170,.13,'sine',.14,0,340);if(type==='slide')this.tone(230,.15,'triangle',.08,0,80);if(type==='perfect'||type==='dodge'){this.tone(523,.27,'sine',.17);this.tone(784,.25,'sine',.13,.06);this.tone(1046,.32,'sine',.09,.12);}if(type==='flame'){this.tone(660,.4,'sine',.16);this.tone(990,.5,'sine',.09,.1);}if(type==='hit'||type==='practice'){this.tone(100,.3,'triangle',.32,0,32);this.tone(59,.25,'sawtooth',.10);}if(type==='boost'||type==='ready'||type==='gate'){[392,523,784,1046].forEach((n,i)=>this.tone(n,.7,'sine',.15,i*.085));}if(type==='end')this.tone(196,.9,'triangle',.15,0,98);if(type==='purchase'){this.tone(523,.2,'sine',.2);this.tone(784,.4,'sine',.18,.12);}}
  update(active,boost){if(!this.enabled||!this.ctx||this.ctx.state!=='running')return;const t=this.ctx.currentTime;this.music.gain.setTargetAtTime(active?.2:.09,t,.8);if(t<this.nextMusic)return;this.nextMusic=t+3.7;const roots=[130.81,146.83,110,164.81];const root=roots[Math.floor(this.phrase/2)%4];[1,1.5,2].forEach((f,i)=>this.tone(root*f,4.1,'sine',.12,i*.15,null,this.music));if(active){const notes=[2,3,2.5,4];for(let i=0;i<4;i++)this.tone(root*notes[(i+this.phrase)%4],.8,'sine',boost?.19:.10,.5+i*.75,null,this.music);}this.phrase++;}
  suspend(){if(this.ctx?.state==='running')this.ctx.suspend().catch(()=>{});}
}
