// 品物の ドット絵（16x16）。'.' は とうめい。色は pal と blocks.mjs の ITEMS[].pal。
export const ICONS = {
  sword: {
    pal: {k: '#1c1a22', B: '#d6d6d6', W: '#ffffff', D: '#979797', G: '#4a3520', H: '#7a5530'},
    map: [
      '..............kk',
      '.............kWk',
      '............kWBk',
      '...........kWBk.',
      '..........kWBk..',
      '.........kWBk...',
      '........kWBk....',
      '..kk...kWBk.....',
      '..kGk.kWBk......',
      '...kGkWBk.......',
      '....kGDk........',
      '....kHGGk.......',
      '...kHk.kGk......',
      '..kHk...kk......',
      '.kHk............',
      '.kk.............',
    ],
  },
  bow: {
    pal: {k: '#1c1a22', H: '#8a5a2a', L: '#b07a3a', S: '#e8e8e8', A: '#9a9a9a'},
    map: [
      '.....kkk........',
      '.....SLHk.......',
      '.....S.kHk......',
      '.....S..kHk.....',
      '.....S...kHk....',
      '.....S....kHk...',
      '.....S....kHk...',
      '..kAAAAAAAAAAk..',
      '.....S....kHk...',
      '.....S....kHk...',
      '.....S...kHk....',
      '.....S..kHk.....',
      '.....S.kHk......',
      '.....SLHk.......',
      '.....kkk........',
      '................',
    ],
  },
  shield: {
    pal: {k: '#1c1a22', I: '#a8a8b0', W: '#a87a40', D: '#7a5528', B: '#d6d6d6'},
    map: [
      '..kkkkkkkkkkkk..',
      '.kIIIIIIIIIIIIk.',
      '.kIWWDWWWWDWWIk.',
      '.kIWWDWWWWDWWIk.',
      '.kIWWDWWWWDWWIk.',
      '.kIWWDWIIWDWWIk.',
      '.kIWWDIBBIDWWIk.',
      '.kIWWDIBBIDWWIk.',
      '.kIWWDWIIWDWWIk.',
      '.kIWWDWWWWDWWIk.',
      '..kIWDWWWWDWIk..',
      '..kIWDWWWWDWIk..',
      '...kIWWWWWWIk...',
      '....kIWWWWIk....',
      '.....kIIIIk.....',
      '......kkkk......',
    ],
  },
  helmet: {
    pal: {k: '#1c1a22', M: '#cfcfcf', L: '#ffffff', D: '#8a8a8a'},
    map: [
      '................',
      '................',
      '................',
      '....kkkkkkkk....',
      '...kLLLMMMMMk...',
      '..kLLMMMMMMMDk..',
      '..kLMMMMMMMMDk..',
      '..kMMMMMMMMMDk..',
      '..kMMkkkkkkMDk..',
      '..kMk......kDk..',
      '..kMk......kDk..',
      '..kkk......kkk..',
      '................',
      '................',
      '................',
      '................',
    ],
  },
  chest: {
    pal: {k: '#1c1a22', M: '#cfcfcf', L: '#ffffff', D: '#8a8a8a'},
    map: [
      '................',
      '..kkkk....kkkk..',
      '.kLMMMk..kMMMDk.',
      '.kLMMMMkkMMMMDk.',
      '.kLMMMMMMMMMMDk.',
      '.kkkLMMMMMMDkkk.',
      '...kLMMMMMMDk...',
      '...kLMMMMMMDk...',
      '...kLMMMMMMDk...',
      '...kLMMMMMMDk...',
      '...kLMMMMMMDk...',
      '...kLMMMMMMDk...',
      '...kLLMMMMDDk...',
      '...kkkkkkkkkk...',
      '................',
      '................',
    ],
  },
  pickaxe: {
    pal: {k: '#1c1a22', M: '#d6d6d6', D: '#8a8a8a', H: '#7a5530'},
    map: [
      '................',
      '....kkkkkk......',
      '...kMMMMMMkk....',
      '....kkkkkMMMk...',
      '.........kHMMk..',
      '........kHkkDMk.',
      '.......kHk..kDk.',
      '......kHk...kDk.',
      '.....kHk....kDk.',
      '....kHk.....kDk.',
      '...kHk.......kk.',
      '..kHk...........',
      '.kHk............',
      '.kk.............',
      '................',
      '................',
    ],
  },
  rod: {
    pal: {k: '#1c1a22', H: '#8a5a2a', S: '#d8d8d8', R: '#d83a3a'},
    map: [
      '..............k.',
      '.............kHS',
      '............kHkS',
      '...........kHk.S',
      '..........kHk..S',
      '.........kHk...S',
      '........kHk....S',
      '.......kHk.....S',
      '......kHk......S',
      '.....kHk.......S',
      '....kHk.......SS',
      '...kHk........S.',
      '..kHk........kRk',
      '.kHk..........k.',
      '.kk.............',
      '................',
    ],
  },
  bread: {
    pal: {k: '#3a220e', L: '#ecbc72', M: '#c98a3c', D: '#8a5524'},
    map: [
      '................',
      '................',
      '................',
      '................',
      '....kkkkkkkk....',
      '..kkLLLLLLLLkk..',
      '.kLLMLLMLLMLLMk.',
      '.kLMMMLMMMLMMMk.',
      'kMMMMMMMMMMMMMMk',
      'kMMMMMMMMMMMMMDk',
      'kDMMMMMMMMMMMDDk',
      '.kDDDDDDDDDDDDk.',
      '..kkkkkkkkkkkk..',
      '................',
      '................',
      '................',
    ],
  },
  apple: {
    pal: {k: '#2a1414', R: '#d8312b', D: '#8f1d18', W: '#ffb0a0', G: '#4fa83a', S: '#6b4a2b'},
    map: [
      '................',
      '.......kk.......',
      '........kS......',
      '....kkk.kSGk....',
      '...kRRRkkkRRk...',
      '..kRWRRRRRRRRk..',
      '.kRWWRRRRRRRRRk.',
      '.kRWRRRRRRRRRRk.',
      '.kRRRRRRRRRRRDk.',
      '.kRRRRRRRRRRRDk.',
      '.kRRRRRRRRRRDDk.',
      '..kRRRRRRRRDDk..',
      '...kRRRkkRRDk...',
      '....kkk..kkk....',
      '................',
      '................',
    ],
  },
  cookie: {
    pal: {k: '#3a220e', M: '#d89a50', C: '#4a2a14'},
    map: [
      '................',
      '................',
      '................',
      '.....kkkkkk.....',
      '...kkMMMMMMkk...',
      '..kMMMCMMMMMMk..',
      '..kMMMMMMMCMMk..',
      '.kMMCMMMMMMMMMk.',
      '.kMMMMMMCMMMMMk.',
      '.kMMMMMMMMMMCMk.',
      '.kMMMCMMMMMMMMk.',
      '..kMMMMMMMCMMk..',
      '..kMMMMMMMMMMk..',
      '...kkMMMMMMkk...',
      '.....kkkkkk.....',
      '................',
    ],
  },
  fish: {
    pal: {k: '#2a1a10', M: '#c88a4a', D: '#8a5a2a'},
    map: [
      '................',
      '................',
      '................',
      '................',
      '................',
      '.....kkkkkk...kk',
      '...kkMMMMMMkk.kM',
      '..kMMMMMMMMMMkkM',
      '.kMkMMMMMMMMMMMk',
      '.kMMMMMMMMMMMMMk',
      '..kDDMMMMMMMMkkD',
      '...kkDDDDDDkk.kD',
      '.....kkkkkk...kk',
      '................',
      '................',
      '................',
    ],
  },
  steak: {
    pal: {k: '#2a1010', R: '#b84a3a', P: '#e8a090', D: '#7a2a20', W: '#f0e8d8'},
    map: [
      '................',
      '................',
      '................',
      '......kkkkk.....',
      '....kkRRRRRkk...',
      '...kRRRRRRRRRk..',
      '..kRRRRPRRRRRRk.',
      '..kRRRPPPRRRRRk.',
      '.kRRRRRPRRRRRDk.',
      '.kRRRRRRRRRRRDk.',
      '.kDRRRRRRRRRDk..',
      '..kDDRRRRRDDk...',
      '...kkDDDDDkWWk..',
      '.....kkkkk.kWWk.',
      '............kk..',
      '................',
    ],
  },
  cake: {
    pal: {k: '#3a2018', W: '#fbf6ee', R: '#e0303a', P: '#f4a0b8', S: '#e8c070', D: '#b88a40'},
    map: [
      '................',
      '................',
      '................',
      '......kRk.......',
      '.......k........',
      '...kkkkkkkkkk...',
      '..kWWWWWWWWWWk..',
      '..kWRWWWWRWWWk..',
      '..kWWWWWWWWWWk..',
      '..kPPWPPPPWPPk..',
      '..kSSSSSSSSSSk..',
      '..kPPPPPPPPPPk..',
      '..kSSSSSSSSSSk..',
      '..kDDDDDDDDDDk..',
      '...kkkkkkkkkk...',
      '................',
    ],
  },
  potion: {
    pal: {k: '#1c1a22', H: '#8a5a2a', G: '#dff4fb', C: '#e8344a', W: '#ffffff', D: '#9c1a2c'},
    map: [
      '................',
      '......kkkk......',
      '......kHHk......',
      '.......kk.......',
      '......kGGk......',
      '......kGGk......',
      '.....kGGGGk.....',
      '....kGCCCCGk....',
      '...kGCWCCCCGk...',
      '...kGCWCCCCGk...',
      '...kGCCCCCCGk...',
      '...kGCCCCCDGk...',
      '....kGCCCDGk....',
      '.....kkkkkk.....',
      '................',
      '................',
    ],
  },
  book: {
    pal: {k: '#1c1a22', C: '#6a3ab0', L: '#9a6ad8', W: '#f0e8d0', Y: '#ffd84a'},
    map: [
      '................',
      '................',
      '...kkkkkkkkkk...',
      '..kCCCCCCCCCCk..',
      '..kCLCCCCCCCWk..',
      '..kCLCCCYCCCWk..',
      '..kCLCCYYYCCWk..',
      '..kCLCCCYCCCWk..',
      '..kCLCCCCCCCWk..',
      '..kCLCCCCCCCWk..',
      '..kCLCCCCCCCWk..',
      '..kCLCCCCCCCWk..',
      '..kCCCCCCCCCCk..',
      '...kkkkkkkkkk...',
      '................',
      '................',
    ],
  },
};
